# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  dependencies:
    docker:
      - image: circleci/node:erbium
    steps:
      - checkout
      - run: yarn
      - save_cache:
          key: node-modules-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  lint:
    docker:
      - image: circleci/node:erbium
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-cache-{{ checksum "yarn.lock" }}
      - run: yarn lint

  build:
    docker:
      - image: circleci/node:erbium
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-cache-{{ checksum "yarn.lock" }}
      - run: yarn build

  test:
    docker:
      - image: circleci/node:erbium
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-cache-{{ checksum "yarn.lock" }}
      - run: yarn test

  deploy:
    docker:
      - image: circleci/node:erbium
    steps:
      - add_ssh_keys:
          fingerprints:
            - "02:ba:74:bc:22:00:a3:00:3a:88:6f:17:06:f7:0f:d4"
      - run:
          name: Deployment
          command: |
            ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_IP -p $SSH_PORT -v '
            . ~/.nvm/nvm.sh &&
            cd v-blog-2 &&
            git checkout master &&
            git pull &&
            yarn &&
            yarn build &&
            pm2 restart 5'

workflows:
  version: 2
  lint_test_build_deploy:
    jobs:
      - dependencies
      - lint:
          requires:
            - dependencies
      - test:
          requires:
            - dependencies
      - build:
          requires:
            - test
            - lint
          filters:
            branches:
              only:
                - develop
                - master
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build

