# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  yarn_install:
    docker:
      - image: circleci/node:erbium
    steps:
      - checkout
      - run: yarn
      - save_cache:
          key: node-modules-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  lint:
    docker:
      - image: circleci/node:erbium
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-cache-{{ checksum "yarn.lock" }}
      - run: yarn lint

  build:
    docker:
      - image: circleci/node:erbium
    steps:
      - restore_cache:
          keys:
            - node-modules-cache-{{ checksum "yarn.lock" }}
      - run: yarn build

workflows:
  version: 2
  lint_build:
    jobs:
      - yarn_install
      - build:
          requires:
            - yarn_install
      - lint:
          requires:
            - yarn_install
